# directories
WWW=../../src/web
INSTALLERROOT=/nidb/programs/compiled/nidbinstaller

# copy in the binaries - this assumes the binaries have been built
cp -uv ../../bin/* $INSTALLERROOT/packages/nidb.programs/data/bin/
cp -uv ../../tools/dcm2nii* $INSTALLERROOT/packages/nidb.programs/data/bin/

cp -uv ../../setup/nidb.sql $INSTALLERROOT/packages/nidb.programs/data/

# copy in the web files
cp -ruv $WWW/images $INSTALLERROOT/packages/nidb.web/data/
cp -ruv $WWW/nanodicom $INSTALLERROOT/packages/nidb.web/data/
cp -ruv $WWW/phpCAS $INSTALLERROOT/packages/nidb.web/data/
cp -ruv $WWW/scripts $INSTALLERROOT/packages/nidb.web/data/
cp -ruv $WWW/tools $INSTALLERROOT/packages/nidb.web/data/

cp -uv $WWW/about.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminassessmentforms.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminaudits.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminemail.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminforms.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/admininstances.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminmodalities.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminmodules.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/admin.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminpipelines.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminprojectprotocols.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminprojects.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminqc.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminsites.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/adminusers.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/ajaxapi.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/analysis.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/analysisbuilder.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/api.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/assessments.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/audit.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/beh.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_allocations.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_appointments.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_calendars.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_projects.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_select.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/calendar_users.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/cleanup.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/cluster.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/datadictionary.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/download.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/downloads.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/drugs.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/enrollment.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/experiments.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/fileio.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/filesio.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/footer.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/functions.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/getfile.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/getformfields.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/group_inlineupdate.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/groups.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/header.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/horizontalchart.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/importexperiment.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/importlog.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/import.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/includes_html.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/includes.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/includes_php.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/index.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/instance.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/kashi.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/login.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/longqc.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/managefiles.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/measures.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/menu.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/merge.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/minipipeline.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/mrqcchecklist.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/mrseriesqa.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/nanodicom.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/nidbapi.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/pd.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/pipelines.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/prescriptions.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/preview.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/projectassessments.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/projectchecklist.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/projectreport.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/projects.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/publicdownloads.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/qa.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/ratings.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/redcapimport.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/remoteconnections.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/reports.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/requeststatus.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/scatterplot.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/search.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/series_inlineupdate.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/series.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/setup.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/signup.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/stats.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/status.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/stddevchart.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/studies.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/style.css $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/subject_inlineupdate.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/subjectlist.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/subjects.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/system.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/tags.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/timeline.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/upload.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/users.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/validatepath.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/viewanalysis.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/viewdir.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/viewfile.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/viewimagefile.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/viewimage.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/vitals.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/v.php $INSTALLERROOT/packages/nidb.web/data/
cp -uv $WWW/xygraph.php $INSTALLERROOT/packages/nidb.web/data/
