#ifndef SQUIRRELVERSION_H
#define SQUIRRELVERSION_H

#define SQUIRREL_VERSION_MAJ "1"
#define SQUIRREL_VERSION_MIN "0"

#define UTIL_VERSION_MAJ "2025"
#define UTIL_VERSION_MIN "6"
#define UTIL_BUILD_NUM "370"

#endif // SQUIRRELVERSION_H
