#ifndef SQUIRRELVERSION_H
#define SQUIRRELVERSION_H

#define SQUIRREL_VERSION_MAJ "1"
#define SQUIRREL_VERSION_MIN "0"

#define UTIL_VERSION_MAJ "2026"
#define UTIL_VERSION_MIN "8"
#define UTIL_BUILD_NUM "466"

#endif // SQUIRRELVERSION_H
