#!/bin/sh
# description: DICOM receiver
# chkconfig: 2345 99 00

case "$1" in
'start')
	su nidb -c '/nidb/programs/dcm4che/bin/./dcmrcv NIDB:8104 -dest /nidb/dicomincoming > /dev/null 2>&1 &'
	touch /var/lock/subsys/dcmrcv
	;;
'stop')
	rm -f /var/lock/subsys/dcmrcv
	;;
*)
	echo "Usage: $0 { start | stop }"
	;;
esac
exit 0
