// bids.h
#pragma once

#include <QJsonObject>
#include <QList>
#include <QMap>
#include <QSet>
#include <QString>
#include <QStringList>
#include <QVariantMap>

namespace bids {

/**
 * @brief Lightweight parser output for a single filename.
 *
 * The parser extracts BIDS entities, the suffix, and the file extension.
 */
struct ParseResult {
    QString suffix;
    QString extension;
    QMap<QString, QString> entities;
    bool valid = false;
};

/**
 * @brief Validation result emitted by Validator.
 *
 * The message is intentionally simple so callers can print or log it directly.
 */
struct ValidationMessage {
    enum Severity {
        Info,
        Warning,
        Error
    };

    Severity severity = Info;
    QString subject;
    QString message;
};

/**
 * @brief Represents a single file discovered in the dataset.
 *
 * Reader::makeFileRecord() fills this from the filesystem and parsed filename.
 */
struct FileRecord {
    QString absolutePath;   // full path on disk
    QString relativePath;   // path relative to dataset root
    QString fileName;       // basename

    QString subject;        // parsed subject (sub-XX)
    QString session;        // parsed session (ses-XX)
    QString datatype;       // anat/func/dwi/etc (from directory)
    QString suffix;         // BIDS suffix (bold, T1w, etc)
    QString extension;      // .nii.gz, .json, etc

    QMap<QString, QString> entities; // parsed BIDS entities
    bool parsedAsBids = false;       // whether filename matched BIDS pattern
};

/**
 * @brief Represents a grouped acquisition with its primary data file and companions.
 *
 * Reader::insertFile() assembles these records incrementally.
 */
struct Acquisition {
    QString key;            // canonical entity-based identifier
    QString subject;
    QString session;
    QString datatype;
    QString suffix;
    QMap<QString, QString> entities;

    QList<FileRecord> files;   // all files belonging to this acquisition

    // Primary and companion files
    QString primaryDataPath;   // main data file (e.g. .nii.gz)
    QString jsonSidecarPath;   // exact JSON sidecar
    QString inheritedJsonPath;// fallback JSON from inheritance
    QJsonObject resolvedMetadata; // merged metadata via inheritance

    QString bvalPath;
    QString bvecPath;
    QString eventsPath;

    // Row from scans.tsv if matched
    QVariantMap scansRow;
};

/**
 * @brief Generic container for *_scans.tsv files.
 *
 * The reader stores the table header plus rows as QVariantMap values.
 */
struct ScansTable {
    QString path;
    QStringList columns;
    QList<QVariantMap> rows;
};

/**
 * @brief Represents a single session directory.
 *
 * Sessions hold grouped acquisitions plus any session-level scans table.
 */
struct SessionRecord {
    QString id;
    QList<FileRecord> looseFiles;
    QMap<QString, Acquisition> acquisitions;
    ScansTable scansTable;
};

/**
 * @brief Represents a single subject.
 *
 * Subjects can hold sessions, subject-level acquisitions, and loose files.
 */
struct SubjectRecord {
    QString id;
    QVariantMap participantRow;   // row from participants.tsv
    QList<FileRecord> looseFiles;
    QMap<QString, SessionRecord> sessions;
    QMap<QString, Acquisition> acquisitionsWithoutSession;
    ScansTable scansTable;
};

/**
 * @brief Top-level in-memory index for one BIDS dataset.
 *
 * Reader::readDataset() populates this structure.
 */
struct DatasetIndex {
    QString rootPath;
    QString name;
    QString bidsVersion;
    QJsonObject datasetDescription;

    QStringList participantColumns;
    QList<QVariantMap> participantRows;

    QList<FileRecord> topLevelFiles;
    QMap<QString, SubjectRecord> subjects;

    // All JSON files for metadata resolution
    QList<FileRecord> jsonFiles;

    /**
     * @brief Convenience lookup for a scans.tsv row tied to one acquisition key.
     * @param subject Subject identifier without the sub- prefix
     * @param session Session identifier without the ses- prefix; leave empty for subject-level acquisitions
     * @param acquisitionKey Canonical acquisition key generated by FilenameParser::canonicalStem()
     * @return Matching scans.tsv row, or an empty map if no row was attached
     */
    QVariantMap getScansRow(const QString &subject,
                            const QString &session,
                            const QString &acquisitionKey) const {
        if (!subjects.contains(subject)) return {};
        const SubjectRecord subj = subjects.value(subject);

        if (session.isEmpty()) {
            if (subj.acquisitionsWithoutSession.contains(acquisitionKey))
                return subj.acquisitionsWithoutSession[acquisitionKey].scansRow;
            return {};
        }

        if (!subj.sessions.contains(session)) return {};
        const SessionRecord sess = subj.sessions.value(session);
        if (!sess.acquisitions.contains(acquisitionKey)) return {};
        return sess.acquisitions[acquisitionKey].scansRow;
    }
};

/**
 * @brief Lightweight TSV reader used for participants.tsv and scans.tsv files.
 */
class TsvReader {
public:
    /**
     * @brief Read a tab-separated file into a header list and row maps.
     * @param path Path to the TSV file
     * @param headers Output list of column names from the first row
     * @param rows Output row data keyed by header name
     * @param error Output error message if parsing fails
     * @return True if the file could be read and parsed successfully
     */
    static bool read(const QString &path, QStringList &headers, QList<QVariantMap> &rows, QString &error);
};

/**
 * @brief Parses BIDS-like filenames into entity/value pairs.
 *
 * This is used for grouping files that belong to the same acquisition.
 */
class FilenameParser {
public:
    /**
     * @brief Parse a filename into suffix, extension, and entities.
     * @param fileName Base filename to parse
     * @return Parsed filename components and entity map
     */
    static ParseResult parse(const QString &fileName);

    /**
     * @brief Build a stable acquisition key from parsed entities and suffix.
     * @param entities Parsed BIDS entities such as sub, ses, task, acq, run, and dir
     * @param suffix Acquisition suffix such as bold, T1w, dwi, or events
     * @return Canonical grouping key used to identify one acquisition
     */
    static QString canonicalStem(const QMap<QString, QString> &entities, const QString &suffix);
};

/**
 * @brief Resolves JSON metadata using the BIDS inheritance rules.
 *
 * This merges sidecars from broadest to most specific.
 */
class MetadataResolver {
public:
    /**
     * @brief Resolve metadata for every acquisition in the dataset.
     * @param dataset Fully indexed dataset whose acquisitions should receive resolved metadata
     */
    static void resolveDatasetMetadata(DatasetIndex &dataset);

private:
    static void resolveAcquisitionMetadata(const DatasetIndex &dataset, Acquisition &acq);

    static QList<FileRecord> candidateJsonFiles(const DatasetIndex &dataset, const Acquisition &acq);

    /**
     * @brief Return true if a JSON sidecar applies to one acquisition.
     * @param dataset Dataset index used to resolve relative path relationships
     * @param jsonFile JSON file being tested
     * @param acq Acquisition that may receive metadata from the JSON file
     * @return True if the JSON file is an applicable sidecar for the acquisition
     */
    static bool jsonAppliesToAcquisition(const DatasetIndex &dataset, const FileRecord &jsonFile, const Acquisition &acq);

    /**
     * @brief Measure common directory depth between two relative paths.
     * @param a First relative path
     * @param b Second relative path
     * @return Number of leading path components shared by both paths
     */
    static int commonPrefixDepth(const QString &a, const QString &b);

    /**
     * @brief Read a JSON object from disk.
     * @param path Path to the JSON file
     * @param obj Parsed JSON object on success
     * @return True if the file could be read and parsed as a JSON object
     */
    static bool readJsonObject(const QString &path, QJsonObject &obj);

    /**
     * @brief Merge overlay into base so later values override earlier ones.
     * @param base JSON object to receive the merged values
     * @param overlay JSON object whose values should overwrite base values
     */
    static void mergeJson(QJsonObject &base, const QJsonObject &overlay);
};

/**
 * @brief Main dataset reader.
 *
 * Call readDataset() to build a DatasetIndex from a BIDS root directory.
 */
class Reader {
public:
    /**
     * @brief Read and index a BIDS dataset rooted at rootPath.
     * @param rootPath Root directory of the BIDS dataset
     * @param out Populated dataset index on success
     * @param error Error message if reading fails
     * @return True if the dataset was read successfully
     */
    bool readDataset(const QString &rootPath,
                     DatasetIndex &out,
                     QString &error) const;

private:
    /**
     * @brief Read dataset_description.json and extract required fields.
     * @param path Path to dataset_description.json
     * @param out Dataset index that receives the parsed description fields
     * @param error Error message if the file is missing or invalid
     * @return True if the file exists, parses, and contains required fields
     */
    static bool readDatasetDescription(const QString &path, DatasetIndex &out, QString &error);

    /**
     * @brief Load participants.tsv if present.
     * @param path Path to participants.tsv
     * @param out Dataset index that receives the participants table
     */
    static void readParticipants(const QString &path, DatasetIndex &out);

    /**
     * @brief Build a FileRecord from one filesystem path.
     * @param absPath Absolute filesystem path to the file
     * @param relPath File path relative to the dataset root
     * @return FileRecord populated with parsed filename and path-derived fields
     */
    static FileRecord makeFileRecord(const QString &absPath, const QString &relPath);

    /**
     * @brief Compute the canonical grouping key for one file.
     * @param fr File record whose entities and suffix should be normalized
     * @return Canonical acquisition key derived from the file metadata
     */
    static QString acquisitionKey(const FileRecord &fr);

    /**
     * @brief Return true for extensions that should be grouped into acquisitions.
     * @param ext File extension, including the leading dot
     * @return True if the extension should be grouped with other acquisition files
     */
    static bool isCompanionOrPrimary(const QString &ext);

    /**
     * @brief Add one file to an acquisition and classify its role.
     * @param fr File being added to the acquisition
     * @param acq Acquisition that will receive the file and derived companion paths
     */
    static void classifyIntoAcquisition(const FileRecord &fr, Acquisition &acq);

    /**
     * @brief Ensure the subject container exists before inserting data under it.
     * @param out Dataset index that will receive the subject
     * @param subject Subject identifier without the sub- prefix
     */
    static void ensureSubject(DatasetIndex &out, const QString &subject);

    /**
     * @brief Insert one file into the dataset hierarchy.
     *
     * This determines whether the file is top-level, a scans table, a loose
     * file, or part of a grouped acquisition.
     * @param fr Parsed file record to insert
     * @param out Dataset index that will receive the file
     */
    static void insertFile(const FileRecord &fr, DatasetIndex &out);

    /**
     * @brief Link participants.tsv rows to the matching subject records.
     * @param out Dataset index whose subjects should be matched to participants.tsv rows
     */
    static void attachParticipantRows(DatasetIndex &out);

    /**
     * @brief Identify *_scans.tsv files, which are handled separately from acquisitions.
     * @param fr File record to test
     * @return True if the file is a scans.tsv side table
     */
    static bool isScansTsv(const FileRecord &fr);

    /**
     * @brief Read a subject-level scans table.
     * @param fr File record pointing to the scans.tsv file
     * @param subj Subject record that will receive the parsed table
     */
    static void readScansTable(const FileRecord &fr, SubjectRecord &subj);

    /**
     * @brief Read a session-level scans table.
     * @param fr File record pointing to the scans.tsv file
     * @param sess Session record that will receive the parsed table
     */
    static void readScansTable(const FileRecord &fr, SessionRecord &sess);

    /**
     * @brief Attach scans.tsv rows across the entire dataset hierarchy.
     * @param out Dataset index whose acquisitions should receive scans row matches
     */
    static void attachScansRows(DatasetIndex &out);

    /**
     * @brief Match scans.tsv rows back to acquisitions.
     * @param table Parsed scans.tsv table
     * @param acqs Acquisition map to update with matched scans rows
     */
    static void attachScansRowsToAcquisitionMap(const ScansTable &table, QMap<QString, Acquisition> &acqs);
};

/**
 * @brief Lightweight validator for common dataset-shape problems.
 */
class Validator {
public:
    /**
     * @brief Validate the in-memory dataset index and return warnings/errors.
     * @param ds Dataset index to validate
     * @return List of validation messages describing warnings and errors
     */
    QList<ValidationMessage> validate(const DatasetIndex &ds) const;

private:
    /**
     * @brief Validate participants.tsv shape and subject linkage.
     * @param ds Dataset index to inspect
     * @param out Output list that receives validation messages
     */
    static void validateParticipants(const DatasetIndex &ds, QList<ValidationMessage> &out);

    /**
     * @brief Validate one acquisition for common problems.
     * @param acq Acquisition to inspect
     * @param out Output list that receives validation messages
     */
    static void validateOneAcq(const Acquisition &acq, QList<ValidationMessage> &out);

    /**
     * @brief Walk all acquisitions and validate each one.
     * @param ds Dataset index containing all acquisitions to validate
     * @param out Output list that receives validation messages
     */
    static void validateAcquisitions(const DatasetIndex &ds, QList<ValidationMessage> &out);
};

} // namespace bids
